a_proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from apps.post.views import listar_primeros_post

from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', listar_primeros_post, name='inicio'),
    path('contacto/',contacto, name='contacto'),
    path('acerca/',acerca, name='acerca'),
    path('usuarios/', include('apps.usuarios.urls')),
    path('post/', include('apps.post.urls')),
    path('comentario/', include('apps.comentarios.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

apps/usuarios/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView, LogoutView
 
from .views import RegristrarUsuario, ActualizarUsuario, EliminarUsuario, listar_usuarios,Perfil


app_name = 'apps.usuarios'

urlpatterns = [
    path('registrar/', RegristrarUsuario.as_view(), name='registrar'),
    path('iniciar_sesion/', LoginView.as_view(template_name = 'usuarios/iniciar_sesion.html'), name='iniciar_sesion'),
    path('login/', LoginView.as_view(template_name = 'usuarios/iniciar_sesion_modal.html'), name='login'),
    path('cerrar_sesion/', LogoutView.as_view(), name='cerrar_sesion'),
    path("actualizar_usuario/<int:pk>", ActualizarUsuario.as_view(template_name = 'usuarios/actualizar_usuario.html'), name='actualizar_usuario'),
    path("eliminar_usuario/<int:pk>", EliminarUsuario.as_view(), name='eliminar_usuario'),
    path("listar_usuarios/", listar_usuarios, name='listar_usuarios'),
    path("perfil/<int:pk>", Perfil.as_view(template_name = 'usuarios/perfil.html'), name ='perfil'),
]

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Usuarios(AbstractUser):
    nombre = models.CharField(max_length=20)
    apellido = models.CharField( max_length=20)
    fecha_nacimiento = models.DateField('Fecha_nacimiento', default='2000-1-1')
    es_colaborador = models.BooleanField(default=False)
    imagen = models.ImageField(null=True, blank=True, upload_to='usuarios',default='usuarios/default1.png')

    def __str__(self):
        return self.nombre
    

apps/usuarios/forms.py
from .models import Usuarios
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

class RegistrarUsuariosForm(UserCreationForm):
    class Meta:
        model = Usuarios
        fields = ['nombre','apellido','fecha_nacimiento','username','password1','password2','email','imagen']

    @transaction.atomic
    def save(self):
        user= super().save(commit=False)
        user.is_superuser = False
        user.is_staff = False
        user.save()
        return user

apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Usuarios
from .forms import RegistrarUsuariosForm


# Create your views here.
class RegristrarUsuario(CreateView):
    model = Usuarios
    form_class = RegistrarUsuariosForm
    template_name = 'usuarios/registrar_usuario.html'
    success_url = reverse_lazy('inicio')

class ActualizarUsuario(LoginRequiredMixin,UpdateView):
    model = Usuarios
    fields= ['nombre','apellido','email','fecha_nacimiento', 'imagen']
    template_name = 'usuarios/actualizar_usuario.html'
    success_url = reverse_lazy('inicio')

class EliminarUsuario(LoginRequiredMixin,DeleteView):
    model = Usuarios
    template_name = 'post/confirmar_eliminar.html'
    success_url = reverse_lazy('apps.usuarios:listar_usuarios')

def listar_usuarios(request):
    usuarios = Usuarios.objects.all().exclude(is_superuser = 1)
    template_name = 'usuarios/listar_usuarios.html'
    contexto = {
        "usuarios" : usuarios
    }
    return render(request, template_name, contexto)

class Perfil(CreateView):
    model = Usuarios
    fields= ['nombre','apellido','email','fecha_nacimiento', 'imagen']
    template_name = 'usuarios/perfil.html'
    success_url = reverse_lazy('inicio')

templates/usuarios/actualizar_usuario.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
<title>Registrar Usuario</title>
{% endblock %}
{% block css %}
<link rel='stylesheet' href='{% static "css/registro.css" %}'>
{% endblock %}
{% block contenido %}
<section class="signup">
    <div class="container">
        <div class="row formulario">
            <div class="col-md-8 offset-md-2">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Editar Perfil</h2>
                        <form enctype="multipart/form-data" action="" method="post" class="mi-formulario"
                            id="formulario">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6" id="form_nombre">
                                    <div class="form-group">
                                        <label for="id_nombre"><i class="fa-solid fa-user"></i></i></label>
                                        {{ form.nombre }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Primera letra mayuscula y un minimo de 2
                                        caracteres y un maximo de 20.</p>
                                </div>
                                <div class="col-md-6" id="form_apellido">
                                    <div class="form-group">
                                        <label for="id_apellido">
                                            <i class="fas fa-user"></i>
                                        </label>
                                        {{ form.apellido }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Primera letra mayuscula y un minimo de 2
                                        caracteres y un maximo de 20.</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6" id="form_fecha_nacimiento">
                                    <div class="form-group">
                                        <label for="id_fecha_nacimiento">
                                            <i class="fas fa-calendar"></i>
                                        </label>
                                        {{ form.fecha_nacimiento }}
                                    </div>
                                </div>
                                <div class="col-md-6" id="form_username">
                                    <div class="form-group">
                                        <label for="id_username">
                                            <i class="fas fa-user"></i>
                                        </label>
                                        {{ form.username }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Minimo de 2 caracteres,solo letras y guiones.</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6" id="form_password1">
                                    <div class="form-group">
                                        <label for="id_password1">
                                            <i class="fas fa-lock"></i>
                                        </label>
                                        {{ form.password1 }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Su contraseña no puede ser similar a otros
                                        componentes de su información personal,
                                        debe contener por lo menos 8 caracteres, y al menos 1 caracter especial.</p>
                                </div>
                                <div class="col-md-6" id="form_password2">
                                    <div class="form-group">
                                        <label for="id_password2">
                                            <i class="fas fa-lock"></i>
                                        </label>
                                        {{ form.password2 }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Ambas contraseñas deben ser iguales.</p>
                                </div>
                            </div>
                            <div class="form-group" id="form_email">
                                <label for="id_email">
                                    <i class="fas fa-envelope"></i>
                                </label>
                                {{ form.email }}
                                <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                            </div>
                            <div class="form-group">
                                <p> <i class="fa-solid fa-image"></i>Imagen actual: {{ usuarios.imagen.name }}</p>
                                <div class="container">
                                    <img src="{{ usuarios.imagen.url }}" style="max-width: 100px; height: auto;" ;
                                        alt="">
                                </div>
                                <p>Modificar imagen:
                                    <input type="file" name="imagen" accept="imagen/*" id="id_imagen" placeholder="Imagen"
                                        class="m-0 p-0">
                                </p>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="btn btn-success"
                                    value="Guardar Cambios">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/usuarios/iniciar_sesion.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
<title>Iniciar Sesión</title>
{% endblock %}

{% block css %}
<link rel='stylesheet' href='{% static "css/registro.css" %}'>
{% endblock %}

{% block contenido %}
<section class="signup">
    <div class="container">
        <div class="row formulario">
            <div class="col-md-8 offset-md-2">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Iniciar Sesión</h2>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_username">
                                    <i class="fas fa-user"></i>
                                </label>
                                <input type="text" name="username" value="asda" autofocus="" autocapitalize="none" 
                                autocomplete="username" maxlength="150" required="" id="id_username" placeholder="Nombre de Usuario">
                            </div>
                            <div class="form-group">
                                <label for="id_password">
                                    <i class="fas fa-lock"></i>
                                </label>
                                <input type="password" name="password" autocomplete="current-password" required="" id="id_password"
                                placeholder="Contraseña">
                            </div>
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                            <div class="form-group form-button d-flex justify-content-center align-items-center">
                                <button type="submit" class="btn btn-success">Iniciar Sesión</button>
                            </div>
                            <a href="{% url 'apps.usuarios:registrar' %}" class="signup-image-link">Crear una cuenta</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    document.getElementById("id_password1").placeholder = "Contraseña";
    document.getElementById("id_username1").placeholder = "Nombre de Usuario";
</script>
{% endblock %}

templates/usuarios/iniciar_sesion_modal.html
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Iniciar Sesión</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'apps.usuarios:iniciar_sesion' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <i class="fas fa-user"></i> Nombre de Usuario
                        <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username"
                            maxlength="150" required="" class="form-control" id="id_username">
                    </div>
                    <div class="mb-3">
                        <i class="fas fa-lock"></i> Contraseña
                        <input type="password" name="password" autocomplete="current-password" required=""
                            class="form-control" id="id_password">
                    </div>
                    {% if messages %}
                    <div class="alert alert-danger" role="alert">
                        {% for message in messages %}
                        {{ message }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="d-flex  justify-content-center">
                        <button type="submit" class="btn btn-success">Iniciar Sesión</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="{% url 'apps.usuarios:registrar' %}" class="btn btn-secondary">Registrarse</a>
                <button type="button" class="btn active" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById("id_password").placeholder = "Contraseña";
    document.getElementById("id_username").placeholder = "Nombre de Usuario";
</script>

templates/usuarios/iniciar_sesionmodal.html
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Iniciar Sesión</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'apps.usuarios:iniciar_sesion' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <i class="fas fa-user"></i> Nombre de Usuario
                        <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username"
                            maxlength="150" required="" class="form-control" id="id_username">
                    </div>
                    <div class="mb-3">
                        <i class="fas fa-lock"></i> Contraseña
                        <input type="password" name="password" autocomplete="current-password" required=""
                            class="form-control" id="id_password">
                    </div>
                    {% if messages %}
                    <div class="alert alert-danger" role="alert">
                        {% for message in messages %}
                        {{ message }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="d-flex  justify-content-center">
                        <button type="submit" class="btn btn-success">Iniciar Sesión</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="{% url 'apps.usuarios:registrar' %}" class="btn btn-secondary">Registrarse</a>
                <button type="button" class="btn active" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById("id_password").placeholder = "Contraseña";
    document.getElementById("id_username").placeholder = "Nombre de Usuario";
</script>

templates/usuarios/listar_usuarios.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
<title>Listado de usuarios</title>
{% endblock %}

{% block contenido %}

<section data-bs-version="5.1" class="team2 cid-tffTM7TT6b">
    <h2 style="text-align:center; margin-top: 2%;"><strong>Usuarios</strong></h2>
    <div class="container">
        <table class="table table-striped">
            <thead>
                <tr style="text-align: center;">
                    <th scope="col">#</th>
                    <th scope="col"></th>
                    <th scope="col">Username</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Email</th>
                    <th scope="col">Fecha de Nacimiento</th>
                    <th scope="col">Colaborador</th>
                    <th scope="col">Fecha de Registro</th>
                </tr>
            </thead>
            {% for item in usuarios %}
            <tbody style="text-align: center;">
                <tr>
                    <th scope="row">{{item.pk}}</th>
                    <td><img src="{{item.imagen.url}}" alt="perfil" width="40" height="auto" class="rounded-circle flex-shrink-0"></td>
                    <td>{{item.username}}</td>
                    <td>{{item.nombre}}</td>
                    <td>{{item.apellido}}</td>
                    <td>{{item.email}}</td>
                    <td>{{item.fecha_nacimiento}}</td>
                    <td>{{item.es_colaborador}}</td>
                    <td>{{item.date_joined}}</td>
                    {% if item.is_superuser %}
                    {% else %}
                    <td><a href="{% url 'apps.usuarios:eliminar_usuario' item.pk %}" class="btn btn-outline-dark"
                        style="font-size: small;">Eliminar</a></td>
                    {% endif %} 
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
</section>
{% endblock %}

templates/usuarios/perfil.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
<title>Perfil</title>
{% endblock %}

{% block contenido %}
<section class="seccion-perfil-usuario">

    <div class="perfil-usuario-portada">
        <div class="perfil-usuario-imagen">
            <img src="{{user.imagen.url}}" alt="img-perfil">
        </div>
        <a class="boton-portada" href="{% url 'apps.usuarios:actualizar_usuario' user.pk %}">Editar Perfil</a>
    </div>

    <div class="perfil-usuario-body">
        <div class="perfil-usuario-username">
            <h3 class="titulo">{{user.username}}</h3>
        </div>
        <div class="perfil-usuario-footer">
            <ul class="lista-datos">
                <li><i class="icono fa-solid fa-user"></i> Nombre: {{user}}</li>
                <li><i class="icono fa-solid fa-user"></i> Apellido: {{user.apellido}}</li>
                <li><i class="icono fas fa-envelope"></i> Email: {{user.email}}</li>
                <li><i class="icono fas fa-calendar"></i> Fecha de Nacimiento: {{user.fecha_nacimiento}}</li>
            </ul>
        </div>
    </div>
</section>
{% endblock %}

<a class="boton-portada" href="{% url 'apps.usuarios:actualizar_usuario' user.pk %}">Editar Perfil</a>

templates/usuarios/registrar_usuario.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    <title>Registrar Usuario</title>
{% endblock %}
{% block css %}
    <link rel='stylesheet' href='{% static "css/registro.css" %}'>
{% endblock %}
{% block contenido %}
<section class="signup">
    <div class="container">
        <div class="row formulario">
            <div class="col-md-8 offset-md-2">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Registrarse</h2>
                        <form enctype="multipart/form-data" action="" method="post" class="mi-formulario" id="formulario">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6" id="form_nombre">
                                    <div class="form-group">
                                        <label for="id_nombre"><i class="fa-solid fa-user"></i></i></label>
                                        {{ form.nombre }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Primera letra mayuscula y un minimo de 2 caracteres y un maximo de 20.</p>
                                </div>
                                <div class="col-md-6" id="form_apellido">
                                    <div class="form-group">
                                        <label for="id_apellido">
                                            <i class="fas fa-user"></i>
                                        </label>
                                        {{ form.apellido }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Primera letra mayuscula y un minimo de 2 caracteres y un maximo de 20.</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6" id="form_fecha_nacimiento">
                                    <div class="form-group">
                                        <label for="id_fecha_nacimiento">
                                            <i class="fas fa-calendar"></i>
                                        </label>
                                        {{ form.fecha_nacimiento }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Formato:YYYY-MM-DD</p>
                                </div>
                                <div class="col-md-6" id="form_username">
                                    <div class="form-group">
                                        <label for="id_username">
                                            <i class="fas fa-user"></i>
                                        </label>
                                        {{ form.username }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Minimo de 2 caracteres,solo letras y guiones.</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6" id="form_password1">
                                    <div class="form-group">
                                        <label for="id_password1">
                                            <i class="fas fa-lock"></i>
                                        </label>
                                        {{ form.password1 }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Su contraseña no puede ser similar a otros componentes de su información personal,
                                        debe contener por lo menos 8 caracteres, y al menos 1 caracter especial.</p>
                                </div>
                                <div class="col-md-6" id="form_password2">
                                    <div class="form-group">
                                        <label for="id_password2">
                                            <i class="fas fa-lock"></i>
                                        </label>
                                        {{ form.password2 }}
                                        <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                                    </div>
                                    <p class="formulario__input-error">Ambas contraseñas deben ser iguales.</p>
                                </div>
                            </div>
                            <div class="form-group" id="form_email">
                                <label for="id_email">
                                    <i class="fas fa-envelope"></i>
                                </label>
                                {{ form.email }}
                                <i class="formulario__icon-error fa-solid fa-circle-xmark" id="icon"></i>
                            </div>
                            <div class="form-group">
                                <label for="id_imagen">
                                    <i class="fas fa-image"></i>
                                </label>
                                {{ form.imagen }}
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="btn btn-success" value="Crear cuenta">
                            </div>
                            <a href="{% url 'apps.usuarios:iniciar_sesion' %}" class="signup-image-link">Ya estoy registrado</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src='{% static "js/registro.js" %}'></script>
{% endblock %}